apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: componentdefinition-A
  namespace: vela-system
spec:
  version: v2.1.2
  workload:
    definition:
      apiVersion: v1
      kind: ConfigMap
  schematic:
    cue:
      template: |
        output: {
          apiVersion: "v1"
          kind:       "ConfigMap"
          metadata: {
            name: context.name
          }
          data: parameter.data
        }

        parameter: {
          // Data in key-value pairs to be stored in the ConfigMap
          data: [string]: string
        }
