# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: componentdefinitions.core.oam.dev
  namespace: vela-system
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: vela-system
          name: vela-core-webhook
          path: /mutate-core-oam-dev-v1beta2-componentdefinition
          port: 443
      conversionReviewVersions: ["v1beta1","v1beta2"]
